apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloud-app-prod
  namespace: kube-system
spec:
  project: default
  source:
    repoURL: git@github.com:Odjeissi/ks8.git
    targetRevision: HEAD
    path: kustomize/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
