apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret

metadata:
  name: app-external-secret

spec:
  # Name of the ExternalSecret created in matching namespaces
  externalSecretName: kube-secret

  # Select namespaces that have the label app=cloud-app
  namespaceSelectors:
    - matchLabels:
        app: cloud-app

  externalSecretSpec:
    refreshInterval: 1h
    refreshPolicy: Periodic

    secretStoreRef:
      name: aws-secrets-manager
      kind: ClusterSecretStore

    target:
      name: kube-secret
      creationPolicy: Owner

    dataFrom:
      - extract:
          key: app_Secrets
