apiVersion: v1
kind: Namespace
metadata:
  name: dev
  labels:
    app: cloud-app # This label allows the ClusterExternalSecret to select this namespace
---
apiVersion: v1
kind: Namespace
metadata:
  name: prod
  labels:
    app: cloud-app
---
apiVersion: v1
kind: Namespace
metadata:
  name: stage
  labels:
    app: cloud-app
