apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
namePrefix: dev-
namespace: dev
labels:
  - pairs:
      app: my-app
    includeSelectors: true
    includeTemplates: true
images:
  - name: 497862080253.dkr.ecr.us-east-1.amazonaws.com/project/my-app
    newTag: f230c049
patches:
  - path: replicas-patch.yaml
    target:
      kind: Deployment
      name: app-deployment
