apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: aws-secrets-manager
  annotations:
    ## Add this annotation to disable controller warning events for unmaintained stores
    external-secrets.io/ignore-maintenance-checks: "true"
spec:
  # You can specify retry settings for the http connection
  # these fields allow you to set a maxRetries before failure, and
  # an interval between the retries.
  retrySettings:
    maxRetries: 5
    retryInterval: "10s"

  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secret-operator
            namespace: kube-system
